### ISSUE TITLE
'stream-chat' ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by yuniit** [RocketChat/meteor-streamer#43]
Hello
I got this error after add the package to my project 

**Version**
Meteor 1.8.1      
rocketchat:streamer@1.1.0

```js 
I20210225-16:41:52.222(7)? Exception while invoking method 'stream-chat' ReferenceError: _ is not defined
I20210225-16:41:52.222(7)?     at changedPayload (packages/rocketchat:streamer/server/server.js:16:2)
I20210225-16:41:52.222(7)?     at Streamer._emit (packages/rocketchat:streamer/server/server.js:386:15)
I20210225-16:41:52.222(7)?     at MethodInvocation.method.(anonymous function) (packages/rocketchat:streamer/server/server.js:365:12)
I20210225-16:41:52.223(7)?     at MethodInvocation.methodMap.(anonymous function) (packages/montiapm:agent/lib/hijack/wrap_session.js:161:30)
I20210225-16:41:52.223(7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20210225-16:41:52.223(7)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20210225-16:41:52.223(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20210225-16:41:52.223(7)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20210225-16:41:52.223(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20210225-16:41:52.223(7)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20210225-16:41:52.233(7)?     at new Promise (<anonymous>)
I20210225-16:41:52.233(7)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20210225-16:41:52.234(7)?     at packages/montiapm:agent/lib/hijack/wrap_session.js:52:38
I20210225-16:41:52.234(7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20210225-16:41:52.234(7)?     at Session.sessionProto.protocol_handlers.method (packages/montiapm:agent/lib/hijack/wrap_session.js:51:44)
I20210225-16:41:52.234(7)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by maxnowack** [comment]
Hey @yuniit, try to add the `underscore` package to your meteor app 🙂

**Comment by yuniit** [comment]
@maxnowack  Thank for early reply. I still got this error after `meteor npm i underscore`

**Comment by maxnowack** [comment]
No, not the npm package. Try `meteor add underscore` 😉

**Comment by yuniit** [comment]
Got it work to work. Thank for your time for helping.
