### ISSUE TITLE
Match error: Expected string, got null

### ISSUE THREAD

**Issue by maxnowack** [RocketChat/meteor-streamer#7]
yesterday, I've migrated from arunoda's package to `rocketchat:streamer`. Sometimes, I get the following Exception:

```
Error: Match error: Expected string, got null
    at exports.check (packages/check/match.js:34:1)
    at Subscription.<anonymous> (packages/rocketchat:streamer/server/server.js:264:4)
    at packages/matb33_collection-hooks/collection-hooks.js:275:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Subscription._handler (packages/matb33_collection-hooks/collection-hooks.js:274:1)
    at packages/check/match.js:107:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1701:18)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17) 
```

It seems like the `null` was passed as the eventName to the streamer subscription. I always pass an eventName to the `on` method of a stream. Do you have an idea whats going on here?

**Comment by rodrigok** [comment]
@maxnowack not really, can you debug? You can clone de package code and put inside the folder `packages` in you project, then you can add some console.log to witch data you are receiving.

**Comment by FGM** [comment]
We had a similar problem on a streams to stream upgrade. It happened when

- user is connected to the Meteor 1.3.2.4 appplication using streams
- we deploy the 1.4.1.1 application using streamer
- the client attempts reconnect and emits from server trigger this error
- in our case, specific logic in the 1.4/streamer cod ereloads the client and the error no longer appears

If this is the same issue, it can be avoided by logging clients out during app upgrade.

**Comment by maxnowack** [comment]
Ah ok. Yes, this could definitely be the issue. After a while, the error doesn't occurs anymore in my app.
